"""add max participants to hackathons

Revision ID: 473d29e7e94f
Revises: ed5103303e64
Create Date: 2026-08-16 06:54:36.789238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473d29e7e94f'
down_revision: Union[str, Sequence[str], None] = 'ed5103303e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'hackathons',
    sa.Column(
        'max_participants',
        sa.Integer(),
        nullable=False,
        server_default='100'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'max_participants')
    # ### end Alembic commands ###
