"""create judges table

Revision ID: 7699f8ab1956
Revises: 9e0369b81386
Create Date: 2026-08-16 14:55:17.482466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7699f8ab1956'
down_revision: Union[str, Sequence[str], None] = '9e0369b81386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'judge_id', name='uq_hackathon_judge')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judges')
    # ### end Alembic commands ###
