"""add registration status

Revision ID: d67ef7760a74
Revises: 473d29e7e94f
Create Date: 2026-08-16 11:09:47.999813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67ef7760a74'
down_revision: Union[str, Sequence[str], None] = '473d29e7e94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'registrations',
    sa.Column(
        'status',
        sa.String(length=50),
        nullable=False,
        server_default='registered'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'status')
    # ### end Alembic commands ###
